import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ padding: 10 }}>
        {/* forces suspense boundaries to be hit */}
        <Link href="/" prefetch={false}>
          Home
        </Link>
        &nbsp;
        <Link href="/dashboard">Dashboard</Link>
        &nbsp;
        <Link href="/dashboard/settings">Dashboard Settings</Link>
        <div>Global Layout!</div>
        {children}
      </body>
    </html>
  )
}
